export enum AuthEnums{
    LOGIN_REQUEST = 'LOGIN_REQUEST',
    LOGIN_SUCCESS = 'LOGIN_REQUEST/fulfilled',
    LOGIN_FAILURE = 'LOGIN_REQUEST/rejected',
    LOGOUT_REQUEST = 'LOGOUT_REQUEST',
    LOGOUT_SUCCESS = 'LOGOUT_REQUEST/fulfilled',
    LOGOUT_FAILURE = 'LOGOUT_REQUEST/rejected',
    REGISTER_REQUEST = 'REGISTER_REQUEST',
    REGISTER_SUCCESS = 'REGISTER_REQUEST/fulfilled',
    REGISTER_FAILURE = 'REGISTER_REQUEST/rejected',
}