export enum ScoreEnums{
    GET_SCORES_REQUEST = 'GET_SCORES_REQUEST',
    GET_SCORES_SUCCESS = 'GET_SCORES_REQUEST/fulfilled',
    GET_SCORES_FAILURE = 'GET_SCORES_REQUEST/rejected',
    POST_SCORE_REQUEST = 'POST_SCORE_REQUEST',
    POST_SCORE_SUCCESS = 'POST_SCORE_REQUEST/fulfilled',
    POST_SCORE_FAILURE = 'POST_SCORE_REQUEST/rejected',
}