export enum UserEnums{
    GET_USER_REQUEST = 'GET_USERS_REQUEST',
    GET_USER_SUCCESS = 'GET_USERS_REQUEST/fulfilled',
    GET_USER_FAILURE = 'GET_USERS_REQUEST/rejected',
    UPDATE_USER_REQUEST = 'UPDATE_USER_REQUEST',
    UPDATE_USER_SUCCESS = 'UPDATE_USER_REQUEST/fulfilled',
    UPDATE_USER_FAILURE = 'UPDATE_USER_REQUEST/rejected',
}